import Link from "next/link";
import { notFound } from "next/navigation";
const content:Record<string,{title:string;body:React.ReactNode}>={
  delivery:{title:"Delivery information",body:<><p>We provide nationwide doorstep delivery. Delivery timing and the final cost are shown before you confirm your order.</p><ul><li>Standard delivery is typically 2–5 business days.</li><li>Delivery fees start from ₦2,500.</li><li>Your exact delivery charge is displayed before payment.</li></ul></>},
  returns:{title:"Returns & refunds",body:<><p>Eligible items may be returned within the applicable return window.</p><ul><li>The item must be undamaged and resellable.</li><li>Include all original packaging, accessories, manuals and tags.</li><li>Products marked “No Returns” are final sale.</li></ul><p>Contact support with your order number to begin a return.</p></>},
  privacy:{title:"Privacy policy",body:<><p>We use account, address and order information only to operate the store, fulfil purchases, provide support and improve the service. We do not sell your personal data.</p><p>You may request account-data assistance through customer support.</p></>},
  terms:{title:"Terms & conditions",body:<><p>Prices, availability and delivery estimates are confirmed during checkout. Orders are subject to inventory verification and successful payment where applicable.</p><p>Card and bank payments should only be completed through the secure checkout options presented by Taiga Online Shopping Limited.</p></>},
  story:{title:"Our story",body:<><p>Taiga Online Shopping Limited is a Nigerian online marketplace built to make reliable products easier to discover and buy.</p><p>Our goal is simple: dependable shopping, fair value and a customer experience that feels human.</p></>}
};
export default async function HelpPage({params}:{params:Promise<{topic:string}>}){const {topic}=await params,item=content[topic];if(!item)notFound();return <div className="help-page"><header><div className="wrap"><Link href="/" className="logo"><span>T</span>Taiga<small>MARKET</small></Link><Link href="/shop">Continue shopping</Link></div></header><main className="wrap"><Link href="/">← Back to home</Link><span>Taiga customer care</span><h1>{item.title}</h1><article>{item.body}</article><div><a href="mailto:support@taiga.ng">Email support</a><Link href="/shop">Browse products</Link></div></main></div>}
